export default [
  {
    ISO: 'BGD',
    NAME: 'Bangladesh',
    PH_CODE: '880',
    CUR_CODE: 'BDT',
  },
  {
    ISO: 'BEL',
    NAME: 'Belgium',
    PH_CODE: '32',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'BFA',
    NAME: 'Burkina Faso',
    PH_CODE: '226',
    CUR_CODE: 'XOF',
  },
  {
    ISO: 'BGR',
    NAME: 'Bulgaria',
    PH_CODE: '359',
    CUR_CODE: 'BGN',
  },
  {
    ISO: 'BIH',
    NAME: 'Bosnia and Herzegovina',
    PH_CODE: '387',
    CUR_CODE: 'BAM',
  },
  {
    ISO: 'BRB',
    NAME: 'Barbados',
    PH_CODE: '+1-246',
    CUR_CODE: 'BBD',
  },
  {
    ISO: 'WLF',
    NAME: 'Wallis and Futuna',
    PH_CODE: '681',
    CUR_CODE: 'XPF',
  },
  {
    ISO: 'BLM',
    NAME: 'Saint Barthelemy',
    PH_CODE: '590',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'BMU',
    NAME: 'Bermuda',
    PH_CODE: '+1-441',
    CUR_CODE: 'BMD',
  },
  {
    ISO: 'BRN',
    NAME: 'Brunei',
    PH_CODE: '673',
    CUR_CODE: 'BND',
  },
  {
    ISO: 'BOL',
    NAME: 'Bolivia',
    PH_CODE: '591',
    CUR_CODE: 'BOB',
  },
  {
    ISO: 'BHR',
    NAME: 'Bahrain',
    PH_CODE: '973',
    CUR_CODE: 'BHD',
  },
  {
    ISO: 'BDI',
    NAME: 'Burundi',
    PH_CODE: '257',
    CUR_CODE: 'BIF',
  },
  {
    ISO: 'BEN',
    NAME: 'Benin',
    PH_CODE: '229',
    CUR_CODE: 'XOF',
  },
  {
    ISO: 'BTN',
    NAME: 'Bhutan',
    PH_CODE: '975',
    CUR_CODE: 'BTN',
  },
  {
    ISO: 'JAM',
    NAME: 'Jamaica',
    PH_CODE: '+1-876',
    CUR_CODE: 'JMD',
  },
  {
    ISO: 'BVT',
    NAME: 'Bouvet Island',
    PH_CODE: '',
    CUR_CODE: 'NOK',
  },
  {
    ISO: 'BWA',
    NAME: 'Botswana',
    PH_CODE: '267',
    CUR_CODE: 'BWP',
  },
  {
    ISO: 'WSM',
    NAME: 'Samoa',
    PH_CODE: '685',
    CUR_CODE: 'WST',
  },
  {
    ISO: 'BES',
    NAME: 'Bonaire, Saint Eustatius and Saba ',
    PH_CODE: '599',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'BRA',
    NAME: 'Brazil',
    PH_CODE: '55',
    CUR_CODE: 'BRL',
  },
  {
    ISO: 'BHS',
    NAME: 'Bahamas',
    PH_CODE: '+1-242',
    CUR_CODE: 'BSD',
  },
  {
    ISO: 'JEY',
    NAME: 'Jersey',
    PH_CODE: '+44-1534',
    CUR_CODE: 'GBP',
  },
  {
    ISO: 'BLR',
    NAME: 'Belarus',
    PH_CODE: '375',
    CUR_CODE: 'BYR',
  },
  {
    ISO: 'BLZ',
    NAME: 'Belize',
    PH_CODE: '501',
    CUR_CODE: 'BZD',
  },
  {
    ISO: 'RUS',
    NAME: 'Russia',
    PH_CODE: '7',
    CUR_CODE: 'RUB',
  },
  {
    ISO: 'RWA',
    NAME: 'Rwanda',
    PH_CODE: '250',
    CUR_CODE: 'RWF',
  },
  {
    ISO: 'SRB',
    NAME: 'Serbia',
    PH_CODE: '381',
    CUR_CODE: 'RSD',
  },
  {
    ISO: 'TLS',
    NAME: 'East Timor',
    PH_CODE: '670',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'REU',
    NAME: 'Reunion',
    PH_CODE: '262',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'TKM',
    NAME: 'Turkmenistan',
    PH_CODE: '993',
    CUR_CODE: 'TMT',
  },
  {
    ISO: 'TJK',
    NAME: 'Tajikistan',
    PH_CODE: '992',
    CUR_CODE: 'TJS',
  },
  {
    ISO: 'ROU',
    NAME: 'Romania',
    PH_CODE: '40',
    CUR_CODE: 'RON',
  },
  {
    ISO: 'TKL',
    NAME: 'Tokelau',
    PH_CODE: '690',
    CUR_CODE: 'NZD',
  },
  {
    ISO: 'GNB',
    NAME: 'Guinea-Bissau',
    PH_CODE: '245',
    CUR_CODE: 'XOF',
  },
  {
    ISO: 'GUM',
    NAME: 'Guam',
    PH_CODE: '+1-671',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'GTM',
    NAME: 'Guatemala',
    PH_CODE: '502',
    CUR_CODE: 'GTQ',
  },
  {
    ISO: 'SGS',
    NAME: 'South Georgia and the South Sandwich Islands',
    PH_CODE: '',
    CUR_CODE: 'GBP',
  },
  {
    ISO: 'GRC',
    NAME: 'Greece',
    PH_CODE: '30',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'GNQ',
    NAME: 'Equatorial Guinea',
    PH_CODE: '240',
    CUR_CODE: 'XAF',
  },
  {
    ISO: 'GLP',
    NAME: 'Guadeloupe',
    PH_CODE: '590',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'JPN',
    NAME: 'Japan',
    PH_CODE: '81',
    CUR_CODE: 'JPY',
  },
  {
    ISO: 'GUY',
    NAME: 'Guyana',
    PH_CODE: '592',
    CUR_CODE: 'GYD',
  },
  {
    ISO: 'GGY',
    NAME: 'Guernsey',
    PH_CODE: '+44-1481',
    CUR_CODE: 'GBP',
  },
  {
    ISO: 'GUF',
    NAME: 'French Guiana',
    PH_CODE: '594',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'GEO',
    NAME: 'Georgia',
    PH_CODE: '995',
    CUR_CODE: 'GEL',
  },
  {
    ISO: 'GRD',
    NAME: 'Grenada',
    PH_CODE: '+1-473',
    CUR_CODE: 'XCD',
  },
  {
    ISO: 'GBR',
    NAME: 'United Kingdom',
    PH_CODE: '44',
    CUR_CODE: 'GBP',
  },
  {
    ISO: 'GAB',
    NAME: 'Gabon',
    PH_CODE: '241',
    CUR_CODE: 'XAF',
  },
  {
    ISO: 'SLV',
    NAME: 'El Salvador',
    PH_CODE: '503',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'GIN',
    NAME: 'Guinea',
    PH_CODE: '224',
    CUR_CODE: 'GNF',
  },
  {
    ISO: 'GMB',
    NAME: 'Gambia',
    PH_CODE: '220',
    CUR_CODE: 'GMD',
  },
  {
    ISO: 'GRL',
    NAME: 'Greenland',
    PH_CODE: '299',
    CUR_CODE: 'DKK',
  },
  {
    ISO: 'GIB',
    NAME: 'Gibraltar',
    PH_CODE: '350',
    CUR_CODE: 'GIP',
  },
  {
    ISO: 'GHA',
    NAME: 'Ghana',
    PH_CODE: '233',
    CUR_CODE: 'GHS',
  },
  {
    ISO: 'OMN',
    NAME: 'Oman',
    PH_CODE: '968',
    CUR_CODE: 'OMR',
  },
  {
    ISO: 'TUN',
    NAME: 'Tunisia',
    PH_CODE: '216',
    CUR_CODE: 'TND',
  },
  {
    ISO: 'JOR',
    NAME: 'Jordan',
    PH_CODE: '962',
    CUR_CODE: 'JOD',
  },
  {
    ISO: 'HRV',
    NAME: 'Croatia',
    PH_CODE: '385',
    CUR_CODE: 'HRK',
  },
  {
    ISO: 'HTI',
    NAME: 'Haiti',
    PH_CODE: '509',
    CUR_CODE: 'HTG',
  },
  {
    ISO: 'HUN',
    NAME: 'Hungary',
    PH_CODE: '36',
    CUR_CODE: 'HUF',
  },
  {
    ISO: 'HKG',
    NAME: 'Hong Kong',
    PH_CODE: '852',
    CUR_CODE: 'HKD',
  },
  {
    ISO: 'HND',
    NAME: 'Honduras',
    PH_CODE: '504',
    CUR_CODE: 'HNL',
  },
  {
    ISO: 'HMD',
    NAME: 'Heard Island and McDonald Islands',
    PH_CODE: ' ',
    CUR_CODE: 'AUD',
  },
  {
    ISO: 'VEN',
    NAME: 'Venezuela',
    PH_CODE: '58',
    CUR_CODE: 'VEF',
  },
  {
    ISO: 'PRI',
    NAME: 'Puerto Rico',
    PH_CODE: '+1-787 and 1-939',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'PSE',
    NAME: 'Palestinian Territory',
    PH_CODE: '970',
    CUR_CODE: 'ILS',
  },
  {
    ISO: 'PLW',
    NAME: 'Palau',
    PH_CODE: '680',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'PRT',
    NAME: 'Portugal',
    PH_CODE: '351',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'SJM',
    NAME: 'Svalbard and Jan Mayen',
    PH_CODE: '47',
    CUR_CODE: 'NOK',
  },
  {
    ISO: 'PRY',
    NAME: 'Paraguay',
    PH_CODE: '595',
    CUR_CODE: 'PYG',
  },
  {
    ISO: 'IRQ',
    NAME: 'Iraq',
    PH_CODE: '964',
    CUR_CODE: 'IQD',
  },
  {
    ISO: 'PAN',
    NAME: 'Panama',
    PH_CODE: '507',
    CUR_CODE: 'PAB',
  },
  {
    ISO: 'PYF',
    NAME: 'French Polynesia',
    PH_CODE: '689',
    CUR_CODE: 'XPF',
  },
  {
    ISO: 'PNG',
    NAME: 'Papua New Guinea',
    PH_CODE: '675',
    CUR_CODE: 'PGK',
  },
  {
    ISO: 'PER',
    NAME: 'Peru',
    PH_CODE: '51',
    CUR_CODE: 'PEN',
  },
  {
    ISO: 'PAK',
    NAME: 'Pakistan',
    PH_CODE: '92',
    CUR_CODE: 'PKR',
  },
  {
    ISO: 'PHL',
    NAME: 'Philippines',
    PH_CODE: '63',
    CUR_CODE: 'PHP',
  },
  {
    ISO: 'PCN',
    NAME: 'Pitcairn',
    PH_CODE: '870',
    CUR_CODE: 'NZD',
  },
  {
    ISO: 'POL',
    NAME: 'Poland',
    PH_CODE: '48',
    CUR_CODE: 'PLN',
  },
  {
    ISO: 'SPM',
    NAME: 'Saint Pierre and Miquelon',
    PH_CODE: '508',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'ZMB',
    NAME: 'Zambia',
    PH_CODE: '260',
    CUR_CODE: 'ZMK',
  },
  {
    ISO: 'ESH',
    NAME: 'Western Sahara',
    PH_CODE: '212',
    CUR_CODE: 'MAD',
  },
  {
    ISO: 'EST',
    NAME: 'Estonia',
    PH_CODE: '372',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'EGY',
    NAME: 'Egypt',
    PH_CODE: '20',
    CUR_CODE: 'EGP',
  },
  {
    ISO: 'ZAF',
    NAME: 'South Africa',
    PH_CODE: '27',
    CUR_CODE: 'ZAR',
  },
  {
    ISO: 'ECU',
    NAME: 'Ecuador',
    PH_CODE: '593',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'ITA',
    NAME: 'Italy',
    PH_CODE: '39',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'VNM',
    NAME: 'Vietnam',
    PH_CODE: '84',
    CUR_CODE: 'VND',
  },
  {
    ISO: 'SLB',
    NAME: 'Solomon Islands',
    PH_CODE: '677',
    CUR_CODE: 'SBD',
  },
  {
    ISO: 'ETH',
    NAME: 'Ethiopia',
    PH_CODE: '251',
    CUR_CODE: 'ETB',
  },
  {
    ISO: 'SOM',
    NAME: 'Somalia',
    PH_CODE: '252',
    CUR_CODE: 'SOS',
  },
  {
    ISO: 'ZWE',
    NAME: 'Zimbabwe',
    PH_CODE: '263',
    CUR_CODE: 'ZWL',
  },
  {
    ISO: 'SAU',
    NAME: 'Saudi Arabia',
    PH_CODE: '966',
    CUR_CODE: 'SAR',
  },
  {
    ISO: 'ESP',
    NAME: 'Spain',
    PH_CODE: '34',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'ERI',
    NAME: 'Eritrea',
    PH_CODE: '291',
    CUR_CODE: 'ERN',
  },
  {
    ISO: 'MNE',
    NAME: 'Montenegro',
    PH_CODE: '382',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'MDA',
    NAME: 'Moldova',
    PH_CODE: '373',
    CUR_CODE: 'MDL',
  },
  {
    ISO: 'MDG',
    NAME: 'Madagascar',
    PH_CODE: '261',
    CUR_CODE: 'MGA',
  },
  {
    ISO: 'MAF',
    NAME: 'Saint Martin',
    PH_CODE: '590',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'MAR',
    NAME: 'Morocco',
    PH_CODE: '212',
    CUR_CODE: 'MAD',
  },
  {
    ISO: 'MCO',
    NAME: 'Monaco',
    PH_CODE: '377',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'UZB',
    NAME: 'Uzbekistan',
    PH_CODE: '998',
    CUR_CODE: 'UZS',
  },
  {
    ISO: 'MMR',
    NAME: 'Myanmar',
    PH_CODE: '95',
    CUR_CODE: 'MMK',
  },
  {
    ISO: 'MLI',
    NAME: 'Mali',
    PH_CODE: '223',
    CUR_CODE: 'XOF',
  },
  {
    ISO: 'MAC',
    NAME: 'Macao',
    PH_CODE: '853',
    CUR_CODE: 'MOP',
  },
  {
    ISO: 'MNG',
    NAME: 'Mongolia',
    PH_CODE: '976',
    CUR_CODE: 'MNT',
  },
  {
    ISO: 'MHL',
    NAME: 'Marshall Islands',
    PH_CODE: '692',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'MKD',
    NAME: 'Macedonia',
    PH_CODE: '389',
    CUR_CODE: 'MKD',
  },
  {
    ISO: 'MUS',
    NAME: 'Mauritius',
    PH_CODE: '230',
    CUR_CODE: 'MUR',
  },
  {
    ISO: 'MLT',
    NAME: 'Malta',
    PH_CODE: '356',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'MWI',
    NAME: 'Malawi',
    PH_CODE: '265',
    CUR_CODE: 'MWK',
  },
  {
    ISO: 'MDV',
    NAME: 'Maldives',
    PH_CODE: '960',
    CUR_CODE: 'MVR',
  },
  {
    ISO: 'MTQ',
    NAME: 'Martinique',
    PH_CODE: '596',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'MNP',
    NAME: 'Northern Mariana Islands',
    PH_CODE: '+1-670',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'MSR',
    NAME: 'Montserrat',
    PH_CODE: '+1-664',
    CUR_CODE: 'XCD',
  },
  {
    ISO: 'MRT',
    NAME: 'Mauritania',
    PH_CODE: '222',
    CUR_CODE: 'MRO',
  },
  {
    ISO: 'IMN',
    NAME: 'Isle of Man',
    PH_CODE: '+44-1624',
    CUR_CODE: 'GBP',
  },
  {
    ISO: 'UGA',
    NAME: 'Uganda',
    PH_CODE: '256',
    CUR_CODE: 'UGX',
  },
  {
    ISO: 'TZA',
    NAME: 'Tanzania',
    PH_CODE: '255',
    CUR_CODE: 'TZS',
  },
  {
    ISO: 'MYS',
    NAME: 'Malaysia',
    PH_CODE: '60',
    CUR_CODE: 'MYR',
  },
  {
    ISO: 'MEX',
    NAME: 'Mexico',
    PH_CODE: '52',
    CUR_CODE: 'MXN',
  },
  {
    ISO: 'ISR',
    NAME: 'Israel',
    PH_CODE: '972',
    CUR_CODE: 'ILS',
  },
  {
    ISO: 'FRA',
    NAME: 'France',
    PH_CODE: '33',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'IOT',
    NAME: 'British Indian Ocean Territory',
    PH_CODE: '246',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'SHN',
    NAME: 'Saint Helena',
    PH_CODE: '290',
    CUR_CODE: 'SHP',
  },
  {
    ISO: 'FIN',
    NAME: 'Finland',
    PH_CODE: '358',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'FJI',
    NAME: 'Fiji',
    PH_CODE: '679',
    CUR_CODE: 'FJD',
  },
  {
    ISO: 'FLK',
    NAME: 'Falkland Islands',
    PH_CODE: '500',
    CUR_CODE: 'FKP',
  },
  {
    ISO: 'FSM',
    NAME: 'Micronesia',
    PH_CODE: '691',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'FRO',
    NAME: 'Faroe Islands',
    PH_CODE: '298',
    CUR_CODE: 'DKK',
  },
  {
    ISO: 'NIC',
    NAME: 'Nicaragua',
    PH_CODE: '505',
    CUR_CODE: 'NIO',
  },
  {
    ISO: 'NLD',
    NAME: 'Netherlands',
    PH_CODE: '31',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'NOR',
    NAME: 'Norway',
    PH_CODE: '47',
    CUR_CODE: 'NOK',
  },
  {
    ISO: 'NAM',
    NAME: 'Namibia',
    PH_CODE: '264',
    CUR_CODE: 'NAD',
  },
  {
    ISO: 'VUT',
    NAME: 'Vanuatu',
    PH_CODE: '678',
    CUR_CODE: 'VUV',
  },
  {
    ISO: 'NCL',
    NAME: 'New Caledonia',
    PH_CODE: '687',
    CUR_CODE: 'XPF',
  },
  {
    ISO: 'NER',
    NAME: 'Niger',
    PH_CODE: '227',
    CUR_CODE: 'XOF',
  },
  {
    ISO: 'NFK',
    NAME: 'Norfolk Island',
    PH_CODE: '672',
    CUR_CODE: 'AUD',
  },
  {
    ISO: 'NGA',
    NAME: 'Nigeria',
    PH_CODE: '234',
    CUR_CODE: 'NGN',
  },
  {
    ISO: 'NZL',
    NAME: 'New Zealand',
    PH_CODE: '64',
    CUR_CODE: 'NZD',
  },
  {
    ISO: 'NPL',
    NAME: 'Nepal',
    PH_CODE: '977',
    CUR_CODE: 'NPR',
  },
  {
    ISO: 'NRU',
    NAME: 'Nauru',
    PH_CODE: '674',
    CUR_CODE: 'AUD',
  },
  {
    ISO: 'NIU',
    NAME: 'Niue',
    PH_CODE: '683',
    CUR_CODE: 'NZD',
  },
  {
    ISO: 'COK',
    NAME: 'Cook Islands',
    PH_CODE: '682',
    CUR_CODE: 'NZD',
  },
  {
    ISO: 'XKX',
    NAME: 'Kosovo',
    PH_CODE: '',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'CIV',
    NAME: 'Ivory Coast',
    PH_CODE: '225',
    CUR_CODE: 'XOF',
  },
  {
    ISO: 'CHE',
    NAME: 'Switzerland',
    PH_CODE: '41',
    CUR_CODE: 'CHF',
  },
  {
    ISO: 'COL',
    NAME: 'Colombia',
    PH_CODE: '57',
    CUR_CODE: 'COP',
  },
  {
    ISO: 'CHN',
    NAME: 'China',
    PH_CODE: '86',
    CUR_CODE: 'CNY',
  },
  {
    ISO: 'CMR',
    NAME: 'Cameroon',
    PH_CODE: '237',
    CUR_CODE: 'XAF',
  },
  {
    ISO: 'CHL',
    NAME: 'Chile',
    PH_CODE: '56',
    CUR_CODE: 'CLP',
  },
  {
    ISO: 'CCK',
    NAME: 'Cocos Islands',
    PH_CODE: '61',
    CUR_CODE: 'AUD',
  },
  {
    ISO: 'CAN',
    NAME: 'Canada',
    PH_CODE: '1',
    CUR_CODE: 'CAD',
  },
  {
    ISO: 'COG',
    NAME: 'Republic of the Congo',
    PH_CODE: '242',
    CUR_CODE: 'XAF',
  },
  {
    ISO: 'CAF',
    NAME: 'Central African Republic',
    PH_CODE: '236',
    CUR_CODE: 'XAF',
  },
  {
    ISO: 'COD',
    NAME: 'Democratic Republic of the Congo',
    PH_CODE: '243',
    CUR_CODE: 'CDF',
  },
  {
    ISO: 'CZE',
    NAME: 'Czech Republic',
    PH_CODE: '420',
    CUR_CODE: 'CZK',
  },
  {
    ISO: 'CYP',
    NAME: 'Cyprus',
    PH_CODE: '357',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'CXR',
    NAME: 'Christmas Island',
    PH_CODE: '61',
    CUR_CODE: 'AUD',
  },
  {
    ISO: 'CRI',
    NAME: 'Costa Rica',
    PH_CODE: '506',
    CUR_CODE: 'CRC',
  },
  {
    ISO: 'CUW',
    NAME: 'Curacao',
    PH_CODE: '599',
    CUR_CODE: 'ANG',
  },
  {
    ISO: 'CPV',
    NAME: 'Cape Verde',
    PH_CODE: '238',
    CUR_CODE: 'CVE',
  },
  {
    ISO: 'CUB',
    NAME: 'Cuba',
    PH_CODE: '53',
    CUR_CODE: 'CUP',
  },
  {
    ISO: 'SWZ',
    NAME: 'Swaziland',
    PH_CODE: '268',
    CUR_CODE: 'SZL',
  },
  {
    ISO: 'SYR',
    NAME: 'Syria',
    PH_CODE: '963',
    CUR_CODE: 'SYP',
  },
  {
    ISO: 'SXM',
    NAME: 'Sint Maarten',
    PH_CODE: '599',
    CUR_CODE: 'ANG',
  },
  {
    ISO: 'KGZ',
    NAME: 'Kyrgyzstan',
    PH_CODE: '996',
    CUR_CODE: 'KGS',
  },
  {
    ISO: 'KEN',
    NAME: 'Kenya',
    PH_CODE: '254',
    CUR_CODE: 'KES',
  },
  {
    ISO: 'SSD',
    NAME: 'South Sudan',
    PH_CODE: '211',
    CUR_CODE: 'SSP',
  },
  {
    ISO: 'SUR',
    NAME: 'Suriname',
    PH_CODE: '597',
    CUR_CODE: 'SRD',
  },
  {
    ISO: 'KIR',
    NAME: 'Kiribati',
    PH_CODE: '686',
    CUR_CODE: 'AUD',
  },
  {
    ISO: 'KHM',
    NAME: 'Cambodia',
    PH_CODE: '855',
    CUR_CODE: 'KHR',
  },
  {
    ISO: 'KNA',
    NAME: 'Saint Kitts and Nevis',
    PH_CODE: '+1-869',
    CUR_CODE: 'XCD',
  },
  {
    ISO: 'COM',
    NAME: 'Comoros',
    PH_CODE: '269',
    CUR_CODE: 'KMF',
  },
  {
    ISO: 'STP',
    NAME: 'Sao Tome and Principe',
    PH_CODE: '239',
    CUR_CODE: 'STD',
  },
  {
    ISO: 'SVK',
    NAME: 'Slovakia',
    PH_CODE: '421',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'KOR',
    NAME: 'South Korea',
    PH_CODE: '82',
    CUR_CODE: 'KRW',
  },
  {
    ISO: 'SVN',
    NAME: 'Slovenia',
    PH_CODE: '386',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'PRK',
    NAME: 'North Korea',
    PH_CODE: '850',
    CUR_CODE: 'KPW',
  },
  {
    ISO: 'KWT',
    NAME: 'Kuwait',
    PH_CODE: '965',
    CUR_CODE: 'KWD',
  },
  {
    ISO: 'SEN',
    NAME: 'Senegal',
    PH_CODE: '221',
    CUR_CODE: 'XOF',
  },
  {
    ISO: 'SMR',
    NAME: 'San Marino',
    PH_CODE: '378',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'SLE',
    NAME: 'Sierra Leone',
    PH_CODE: '232',
    CUR_CODE: 'SLL',
  },
  {
    ISO: 'SYC',
    NAME: 'Seychelles',
    PH_CODE: '248',
    CUR_CODE: 'SCR',
  },
  {
    ISO: 'KAZ',
    NAME: 'Kazakhstan',
    PH_CODE: '7',
    CUR_CODE: 'KZT',
  },
  {
    ISO: 'CYM',
    NAME: 'Cayman Islands',
    PH_CODE: '+1-345',
    CUR_CODE: 'KYD',
  },
  {
    ISO: 'SGP',
    NAME: 'Singapore',
    PH_CODE: '65',
    CUR_CODE: 'SGD',
  },
  {
    ISO: 'SWE',
    NAME: 'Sweden',
    PH_CODE: '46',
    CUR_CODE: 'SEK',
  },
  {
    ISO: 'SDN',
    NAME: 'Sudan',
    PH_CODE: '249',
    CUR_CODE: 'SDG',
  },
  {
    ISO: 'DOM',
    NAME: 'Dominican Republic',
    PH_CODE: '+1-809 and 1-829',
    CUR_CODE: 'DOP',
  },
  {
    ISO: 'DMA',
    NAME: 'Dominica',
    PH_CODE: '+1-767',
    CUR_CODE: 'XCD',
  },
  {
    ISO: 'DJI',
    NAME: 'Djibouti',
    PH_CODE: '253',
    CUR_CODE: 'DJF',
  },
  {
    ISO: 'DNK',
    NAME: 'Denmark',
    PH_CODE: '45',
    CUR_CODE: 'DKK',
  },
  {
    ISO: 'VGB',
    NAME: 'British Virgin Islands',
    PH_CODE: '+1-284',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'DEU',
    NAME: 'Germany',
    PH_CODE: '49',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'YEM',
    NAME: 'Yemen',
    PH_CODE: '967',
    CUR_CODE: 'YER',
  },
  {
    ISO: 'DZA',
    NAME: 'Algeria',
    PH_CODE: '213',
    CUR_CODE: 'DZD',
  },
  {
    ISO: 'USA',
    NAME: 'United States',
    PH_CODE: '1',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'URY',
    NAME: 'Uruguay',
    PH_CODE: '598',
    CUR_CODE: 'UYU',
  },
  {
    ISO: 'MYT',
    NAME: 'Mayotte',
    PH_CODE: '262',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'UMI',
    NAME: 'United States Minor Outlying Islands',
    PH_CODE: '1',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'LBN',
    NAME: 'Lebanon',
    PH_CODE: '961',
    CUR_CODE: 'LBP',
  },
  {
    ISO: 'LCA',
    NAME: 'Saint Lucia',
    PH_CODE: '+1-758',
    CUR_CODE: 'XCD',
  },
  {
    ISO: 'LAO',
    NAME: 'Laos',
    PH_CODE: '856',
    CUR_CODE: 'LAK',
  },
  {
    ISO: 'TUV',
    NAME: 'Tuvalu',
    PH_CODE: '688',
    CUR_CODE: 'AUD',
  },
  {
    ISO: 'TWN',
    NAME: 'Taiwan',
    PH_CODE: '886',
    CUR_CODE: 'TWD',
  },
  {
    ISO: 'TTO',
    NAME: 'Trinidad and Tobago',
    PH_CODE: '+1-868',
    CUR_CODE: 'TTD',
  },
  {
    ISO: 'TUR',
    NAME: 'Turkey',
    PH_CODE: '90',
    CUR_CODE: 'TRY',
  },
  {
    ISO: 'LKA',
    NAME: 'Sri Lanka',
    PH_CODE: '94',
    CUR_CODE: 'LKR',
  },
  {
    ISO: 'LIE',
    NAME: 'Liechtenstein',
    PH_CODE: '423',
    CUR_CODE: 'CHF',
  },
  {
    ISO: 'LVA',
    NAME: 'Latvia',
    PH_CODE: '371',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'TON',
    NAME: 'Tonga',
    PH_CODE: '676',
    CUR_CODE: 'TOP',
  },
  {
    ISO: 'LTU',
    NAME: 'Lithuania',
    PH_CODE: '370',
    CUR_CODE: 'LTL',
  },
  {
    ISO: 'LUX',
    NAME: 'Luxembourg',
    PH_CODE: '352',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'LBR',
    NAME: 'Liberia',
    PH_CODE: '231',
    CUR_CODE: 'LRD',
  },
  {
    ISO: 'LSO',
    NAME: 'Lesotho',
    PH_CODE: '266',
    CUR_CODE: 'LSL',
  },
  {
    ISO: 'THA',
    NAME: 'Thailand',
    PH_CODE: '66',
    CUR_CODE: 'THB',
  },
  {
    ISO: 'ATF',
    NAME: 'French Southern Territories',
    PH_CODE: '',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'TGO',
    NAME: 'Togo',
    PH_CODE: '228',
    CUR_CODE: 'XOF',
  },
  {
    ISO: 'TCD',
    NAME: 'Chad',
    PH_CODE: '235',
    CUR_CODE: 'XAF',
  },
  {
    ISO: 'TCA',
    NAME: 'Turks and Caicos Islands',
    PH_CODE: '+1-649',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'LBY',
    NAME: 'Libya',
    PH_CODE: '218',
    CUR_CODE: 'LYD',
  },
  {
    ISO: 'VAT',
    NAME: 'Vatican',
    PH_CODE: '379',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'VCT',
    NAME: 'Saint Vincent and the Grenadines',
    PH_CODE: '+1-784',
    CUR_CODE: 'XCD',
  },
  {
    ISO: 'ARE',
    NAME: 'United Arab Emirates',
    PH_CODE: '971',
    CUR_CODE: 'AED',
  },
  {
    ISO: 'AND',
    NAME: 'Andorra',
    PH_CODE: '376',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'ATG',
    NAME: 'Antigua and Barbuda',
    PH_CODE: '+1-268',
    CUR_CODE: 'XCD',
  },
  {
    ISO: 'AFG',
    NAME: 'Afghanistan',
    PH_CODE: '93',
    CUR_CODE: 'AFN',
  },
  {
    ISO: 'AIA',
    NAME: 'Anguilla',
    PH_CODE: '+1-264',
    CUR_CODE: 'XCD',
  },
  {
    ISO: 'VIR',
    NAME: 'U.S. Virgin Islands',
    PH_CODE: '+1-340',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'ISL',
    NAME: 'Iceland',
    PH_CODE: '354',
    CUR_CODE: 'ISK',
  },
  {
    ISO: 'IRN',
    NAME: 'Iran',
    PH_CODE: '98',
    CUR_CODE: 'IRR',
  },
  {
    ISO: 'ARM',
    NAME: 'Armenia',
    PH_CODE: '374',
    CUR_CODE: 'AMD',
  },
  {
    ISO: 'ALB',
    NAME: 'Albania',
    PH_CODE: '355',
    CUR_CODE: 'ALL',
  },
  {
    ISO: 'AGO',
    NAME: 'Angola',
    PH_CODE: '244',
    CUR_CODE: 'AOA',
  },
  {
    ISO: 'ATA',
    NAME: 'Antarctica',
    PH_CODE: '',
    CUR_CODE: '',
  },
  {
    ISO: 'ASM',
    NAME: 'American Samoa',
    PH_CODE: '+1-684',
    CUR_CODE: 'USD',
  },
  {
    ISO: 'ARG',
    NAME: 'Argentina',
    PH_CODE: '54',
    CUR_CODE: 'ARS',
  },
  {
    ISO: 'AUS',
    NAME: 'Australia',
    PH_CODE: '61',
    CUR_CODE: 'AUD',
  },
  {
    ISO: 'AUT',
    NAME: 'Austria',
    PH_CODE: '43',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'ABW',
    NAME: 'Aruba',
    PH_CODE: '297',
    CUR_CODE: 'AWG',
  },
  {
    ISO: 'IND',
    NAME: 'India',
    PH_CODE: '91',
    CUR_CODE: 'INR',
  },
  {
    ISO: 'ALA',
    NAME: 'Aland Islands',
    PH_CODE: '+358-18',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'AZE',
    NAME: 'Azerbaijan',
    PH_CODE: '994',
    CUR_CODE: 'AZN',
  },
  {
    ISO: 'IRL',
    NAME: 'Ireland',
    PH_CODE: '353',
    CUR_CODE: 'EUR',
  },
  {
    ISO: 'IDN',
    NAME: 'Indonesia',
    PH_CODE: '62',
    CUR_CODE: 'IDR',
  },
  {
    ISO: 'UKR',
    NAME: 'Ukraine',
    PH_CODE: '380',
    CUR_CODE: 'UAH',
  },
  {
    ISO: 'QAT',
    NAME: 'Qatar',
    PH_CODE: '974',
    CUR_CODE: 'QAR',
  },
  {
    ISO: 'MOZ',
    NAME: 'Mozambique',
    PH_CODE: '258',
    CUR_CODE: 'MZN',
  },
];
